In [32]:
import numpy as np
import pandas as pd
import math
import csv 

from sklearn.decomposition import PCA

In [46]:
array_test = np.load('data/test.npy', allow_pickle=True)
array_train = np.load('data/train.npy', allow_pickle=True)

In [47]:
y_test = array_test[:,[-1]]
y_train = array_train[:,[-1]]

In [48]:
array_test = np.delete(array_test, -1, axis=1)
array_train = np.delete(array_train, -1, axis=1)

In [81]:
def pca(dataMat, topNfeat):
    meanVals = np.mean(dataMat, axis=0)
    meanRemoved = dataMat - meanVals  # 标准化（去均值）
    covMat = np.cov(meanRemoved.astype(float), rowvar=False)
    eigVals, eigVets = np.linalg.eig(np.mat(covMat))  # 计算矩阵的特征值和特征向量
    eigValInd = np.argsort(eigVals)  # 将特征值从小到大排序，返回的是特征值对应的数组里的下标
    eigValInd = eigValInd[:-(topNfeat + 1):-1]  # 保留最大的前K个特征值
    redEigVects = eigVets[:, eigValInd]  # 对应的特征向量
    lowDDatMat = meanRemoved * redEigVects  # 将数据转换到低维新空间
    reconMat = (lowDDatMat * redEigVects.T) + meanVals  # 还原原始数据
    # print("reconMat: ")
    # print(reconMat[0])
    return lowDDatMat


In [28]:
X_1 = pca(array_train, 1)
X_5 = pca(array_train, 5)
X_10 = pca(array_train, 10)

In [13]:
Y_1 = pca(array_test, 1)
Y_5 = pca(array_test, 5)
Y_10 = pca(array_test, 10)

In [14]:
np.save('data/X_1.npy',  X_1)
np.save('data/X_5.npy',  X_5)
np.save('data/X_10.npy', X_10)
np.save('data/Y_1.npy',  Y_1)
np.save('data/Y_5.npy',  Y_5)
np.save('data/Y_10.npy', Y_10)

In [50]:
p = PCA(n_components=1)
X_1 = p.fit_transform(array_train)
Y_1 = p.transform(array_test)

In [55]:
p = PCA(n_components=2)
X_2 = p.fit_transform(array_train)
Y_2 = p.transform(array_test)

In [51]:
p = PCA(n_components=5)
X_5 = p.fit_transform(array_train)
Y_5 = p.transform(array_test)

In [52]:
p = PCA(n_components=10)
X_10 = p.fit_transform(array_train)
Y_10 = p.transform(array_test)

In [56]:
p = PCA(n_components=15)
X_15 = p.fit_transform(array_train)
Y_15 = p.transform(array_test)

In [57]:
p = PCA(n_components=20)
X_20 = p.fit_transform(array_train)
Y_20 = p.transform(array_test)

In [58]:
p = PCA(n_components=25)
X_25 = p.fit_transform(array_train)
Y_25 = p.transform(array_test)

In [59]:
p = PCA(n_components=30)
X_30 = p.fit_transform(array_train)
Y_30 = p.transform(array_test)

In [60]:
np.save('data/X_1.npy',  X_1)
np.save('data/X_2.npy',  X_2)
np.save('data/X_5.npy',  X_5)
np.save('data/X_10.npy', X_10)
np.save('data/X_15.npy', X_15)
np.save('data/X_20.npy', X_20)
np.save('data/X_25.npy', X_25)
np.save('data/X_30.npy', X_30)

np.save('data/Y_1.npy',  Y_1)
np.save('data/Y_2.npy',  Y_2)
np.save('data/Y_5.npy',  Y_5)
np.save('data/Y_10.npy', Y_10)
np.save('data/Y_15.npy', Y_15)
np.save('data/Y_20.npy', Y_20)
np.save('data/Y_25.npy', Y_25)
np.save('data/Y_30.npy', Y_30)

In [78]:
p = PCA(n_components=4)
x = np.array([[1, 4, 1, 4, 5], [5, 2, 4, 4, 5], [3, 6, 3, 1, 2], [1, 3, 2, 1, 3]])
# x = np.array([[-2, 1, -2, 1, 2], [1, -2, 0, 0, 1], [0, 3, 0, -2, -1], [-1, 1, 0, -1, 1]])
y = p.fit_transform(x)

In [77]:
print(y)

[[-1.17700350e+00  2.62827647e+00 -2.86051708e-01  8.57558347e-17]
 [-2.42774382e+00 -2.10753965e+00 -1.98334492e-01  8.57558347e-17]
 [ 3.21442942e+00 -6.44387750e-01 -3.56662188e-01  8.57558347e-17]
 [ 3.90317889e-01  1.23650937e-01  8.41048388e-01  8.57558347e-17]]


In [79]:
print(y)

[[ 2.66221603e-01  2.69647682e+00 -1.01643436e+00  1.85040385e-16]
 [ 3.70806954e+00 -1.25487793e+00  2.24725749e-01  1.85040385e-16]
 [-2.37514254e+00 -2.10051047e+00 -9.06396004e-01  1.85040385e-16]
 [-1.59914861e+00  6.58911569e-01  1.69810461e+00  1.85040385e-16]]


In [84]:
x = np.array([[1, 4, 1, 4, 5], [5, 2, 4, 4, 5], [3, 6, 3, 1, 2], [1, 3, 2, 1, 3]])
y = pca(x, 2)
print(y)

[[-0.2662216  -2.69647682]
 [-3.70806954  1.25487793]
 [ 2.37514254  2.10051047]
 [ 1.59914861 -0.65891157]]
